<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Listagem</title>
        <link href="css/bootstrap-theme.css" rel="stylesheet" type="text/css"/>
        <link href="css/bootstrap.css" rel="stylesheet" type="text/css"/>
        <link href="css/blue/style.css" rel="stylesheet" type="text/css"/>
        <link href="css/listagem-css.css" rel="stylesheet" type="text/css"/>
        <script src="js/jquery-3.1.0.min.js" type="text/javascript"></script>
        <script src="js/bootstrap.js" type="text/javascript"></script>
        <script src="js/jquery.tablesorter.min.js" type="text/javascript"></script>
        <script src="js/jquery-listagem.js" type="text/javascript"></script>
    </head>
    <body>
        <header id="cabecalho">
            <div class="container-fluid">
                <div class="row">
                    <nav class="navbar navbar-inverse navbar-fixed-top">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu_dcc" aria-expanded="false">
                                    <span class="sr-only">Listagem Clientes</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="index.php">
                                    Listagem de Clientes
                                </a>
                            </div>
                            <div class="collapse navbar-collapse">
                                <ul class="nav navbar-nav">
                                    <li>
                                        <a href="#"></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </header>
        
        <section id="listagem" style="margin-top: 70px;">
            <div class="container">
                <div class="row">
                    <table class="table table-hover col-lg-12 tablesorter" id="tb_clientes">
                        <thead>
                            <tr>
                                <th class="col-lg-1">#</th>
                                <th class="col-lg-8">Nome</th>
                                <th class="col-lg-2">Tipo</th>
                                <th class="col-lg-1">Estrelas</th>
                            </tr>
                        </thead>
                        <tbody>
                <?php
                    $i=1;
                    foreach ($clientes as $cliente) {
                ?>
                            <tr>
                                <td><?php echo $i;?></td>
                                <td class="nome"><?php echo $cliente->getNome();?></td>
                                <td class="tipo"><?php echo $cliente->getTipo();?></td>
                                <td class="tipo"><?php echo $cliente->getImportancia();?></td>
                                <td class="hidden cpf"><?php echo $cliente->getDocumento();?></td>
                                <td class="hidden end"><?php echo $cliente->getEndereco();?></td>
                                <td class="hidden cel"><?php echo $cliente->getTelefone();?></td>
                                <td class="hidden endCobranca"><?php echo $cliente->getEndereço_cobranca();?></td>
                            </tr>
                <?php
                        $i++;
                    }
                ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
        
        <!--RESPONSAVEL PELOS MODAIS-->
        <section id="modais">
            <div class="modal fade" tabindex="-1" role="dialog" id="modal-informacao">
                <div class="modal-dialog modal-sm" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Informações</h4>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <h5 class="col-lg-12" id="nome">Nome: </h5>
                                <p class="col-lg-12" id="cpf">CPF: </p>
                                <p class="col-lg-12" id="end">END: </p>
                                <p class="col-lg-12" id="cel">CEL: </p>
                                <p class="col-lg-12" id="cel">End Cobrança</p>
                                <p class="col-lg-12" id="end_cobranca"></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>
